Final project
DoomProger/go_final_project pull request #1
Opened 2024-08-20 22:51 UTC by DoomProger

2024-08-26 14:16 UTC, dirtymew requested changes
Привет Никита

отличная работа:
 - документация
 - логирование
 - запуск - task
 - дизайн 

дал комментарии что подправить и улучшить

2024-08-26 14:16 UTC, dirtymew commented on Dockerfile
> +FROM golang:1.22 AS builder
лучше одну версию go использовать 

в go mod go 1.21.8

2024-08-26 14:16 UTC, dirtymew commented on Dockerfile
> +FROM ubuntu
советую взять образ полегче -  alpine например

2024-08-26 14:16 UTC, dirtymew commented on Taskfile.yaml
> +  test-1-App:
в целом одного таска по запуску всех тестов достаточно было бы

2024-08-26 14:16 UTC, dirtymew commented on handlers.go
> +	w.Write([]byte(nextDate))
_ , _ = w.Write(resp)

тут нужно либо явно проигнорировать ошибку или ее логировать

хорошие линтеры на это ругаться будут и не зря

2024-08-26 14:16 UTC, dirtymew commented on handlers.go
> +		if task.Title == "" {
совет - стоит порефакторить хенждеры - очень перегружены проверками

вынести бы их в функции или другой пакет

2024-08-26 14:16 UTC, dirtymew commented on helpers.go
> +package main
совет 

helpers/utils/tools - считается плохой практикой

лучше называть пакеты и файлы как-то  предметно - по тому что код там делает

2024-08-26 14:16 UTC, dirtymew commented on task.go
> +		"SELECT * FROM scheduler WHERE id = :id", sql.Named("id", id))
лучше явно поля указывать чем *

2024-08-26 14:16 UTC, dirtymew commented on task.go
> +
нужно еще ошибку из rows обработать
http://go-database-sql.org/errors.html

2024-08-26 14:16 UTC, dirtymew commented on task.go
> +func (s SchedulerStore) GetTasks(t Task) (TaskResponse, error) {
а зачем тут t Task ?  - вообще я бы обьединил этот и SearchTasks в один

2024-08-26 14:16 UTC, dirtymew commented on settings.go
> +	limit100 int = 100
limit100 - вроде не используется

2024-08-26 14:16 UTC, dirtymew commented on settings.go
> +	Token = ``
будешь авторизацию доделывать?

2024-08-26 14:16 UTC, dirtymew commented on utils.go
> +        CREATE TABLE scheduler (
у тебя есть файл  scheduler.sql - зачем тут дублировать

можно через embed его использовать

2024-08-26 14:16 UTC, dirtymew commented on utils.go
> +func getRepeat(repeat string) (repeatDate, error) {
это бы я вынес в отдельный пакет про даты

2024-08-26 14:16 UTC, dirtymew commented on handlers.go
> +package main
по структуре проекта посмотри https://github.com/golang-standards/project-layout

2024-08-31 20:59 UTC, DoomProger commented on Dockerfile
> +FROM golang:1.22 AS builder
Поправил

2024-08-31 20:59 UTC, DoomProger commented on Dockerfile
> +FROM ubuntu
поправил

2024-08-31 21:00 UTC, DoomProger commented on handlers.go
> +	w.Write([]byte(nextDate))
Тоже поправил (действительно w.Write(resp) возвращает инт и ошибку, что-то не обратил внимание) )

2024-08-31 21:01 UTC, DoomProger commented on Taskfile.yaml
> +  test-1-App:
Это больше для удобства, если на протестиь один какой-то функционал, если прям критично - уберу

2024-08-31 21:01 UTC, DoomProger commented on handlers.go
> +		if task.Title == "" {
В целом проект порефакторил, вроде по легче стало

2024-08-31 21:02 UTC, DoomProger commented on settings.go
> +	limit100 int = 100
Убрал

2024-08-31 21:02 UTC, DoomProger commented on settings.go
> +	Token = ``
Сделал)

2024-08-31 21:02 UTC, DoomProger commented on utils.go
> +        CREATE TABLE scheduler (
Убрал файл, как будто в даннном слкча хардкод лучше (но это не точно) )

2024-08-31 21:03 UTC, DoomProger commented on utils.go
> +func getRepeat(repeat string) (repeatDate, error) {
Так и сделал

2024-08-31 21:03 UTC, DoomProger commented on handlers.go
> +package main
Вроде получилось по этой доке сделать

2024-09-01 14:53 UTC, dirtymew requested changes
Привет Никита

стало сильно лучше

есть несколько моментов которые нужно подправить, а так считаю что задание выполнено

2024-09-01 14:53 UTC, dirtymew commented on Dockerfile
> +COPY go.mod go.sum ./
да в билдер проще все скопировать один раз  COPY . .

2024-09-01 14:53 UTC, dirtymew commented on internal/handlers/auth_handler.go
> +var todoPassword = os.Getenv("TODO_PASSWORD")
ну вот тут считаю помаркой/недоделкой

по идее мы должны работать и без авторизации + нигде не описал как тесты запустить и какой пароль там использовать ... .

обрати внимание @DoomProger

2024-09-01 14:53 UTC, dirtymew commented on internal/services/task_service.go
> +func (ts *TaskService) SearchTasks(search string) (*models.TasksResponse, error) {
тут уже писал - лучше не делать такую связность с models.TasksResponse а все равно возвращать []*models.Task

TasksResponse это скорее относится к api а не к внутреннему устройству сервиса

обрати внимание @DoomProger

2024-09-01 14:53 UTC, dirtymew commented on internal/services/task_service.go
> +func (ts *TaskService) GetTasks() (*models.TasksResponse, error) {
думаю одного метода SearchTasks(search string) бы хватило...

2024-09-01 14:53 UTC, dirtymew commented on internal/repositories/task_repository.go
> +	DB *sql.DB
тут лучше поле db назвать

2024-09-01 14:53 UTC, dirtymew commented on internal/repositories/task_repository.go
> +		"SELECT * FROM scheduler ORDER BY date LIMIT :limit", sql.Named("limit", config.Limit50))
лучше явно указывать поля а не *

2024-09-01 14:53 UTC, dirtymew commented on internal/repositories/task_repository.go
> +
нужно по хорошему еще ошибку из rows обработать
http://go-database-sql.org/errors.html

2024-09-01 14:53 UTC, dirtymew commented on internal/repositories/task_repository.go
> +
нужно еще ошибку из rows обработать
http://go-database-sql.org/errors.html

2024-09-01 14:53 UTC, dirtymew commented on internal/services/task_service.go
> +
вот тут было логично сделать метод TaskDone - и убрать эту логику из хендлера сюда

2024-09-01 14:59 UTC, DoomProger commented on Dockerfile
> +COPY go.mod go.sum ./
Не согласен, зачем в билдере таск файл и т.д.?

2024-09-01 15:02 UTC, DoomProger commented on internal/repositories/task_repository.go
> +		"SELECT * FROM scheduler ORDER BY date LIMIT :limit", sql.Named("limit", config.Limit50))
Почему? Это же обще принятия конструкция в запросах, когда нужно все поля вытащить

2024-09-01 15:11 UTC, DoomProger commented on internal/handlers/auth_handler.go
> +var todoPassword = os.Getenv("TODO_PASSWORD")
Я так понял по заданию, что если есть авторизация то уже не можем.
Описание по запуску тестов добавлю.

2024-09-01 19:34 UTC, DoomProger commented on internal/services/task_service.go
> +func (ts *TaskService) SearchTasks(search string) (*models.TasksResponse, error) {
Поправил

2024-09-01 19:34 UTC, DoomProger commented on internal/repositories/task_repository.go
> +	DB *sql.DB
Поправил

2024-09-01 19:40 UTC, DoomProger commented on internal/repositories/task_repository.go
> +
Если я правильно тебя понял, то:
if err = rows.Close(); err != nil {
		return make([]*models.Task, 0), err
	}
	
Поправил

2024-09-01 19:40 UTC, DoomProger commented on internal/repositories/task_repository.go
> +
Поправил

2024-09-01 20:09 UTC, DoomProger commented on internal/services/task_service.go
> +
Если правильно понял, то вроде правильно реализовал)

2024-09-01 23:13 UTC, DoomProger commented on internal/services/task_service.go
> +func (ts *TaskService) GetTasks() (*models.TasksResponse, error) {
Готово

2024-09-02 12:12 UTC, dirtymew commented on internal/repositories/task_repository.go
> +		"SELECT * FROM scheduler ORDER BY date LIMIT :limit", sql.Named("limit", config.Limit50))
для учебного задания не актуально но есть 2 момента связанных со *
 - порядок полей - будет как в бд и он может моменяться, тогда нужно будет менять запрос
 - кол-во полей - может приходить сильно больше данных чем ты ожидаешь
поэтому стоит запрашивать из бд то что нужно  и как нужно - а не все подряд

2024-09-02 12:14 UTC, dirtymew commented on Dockerfile
> +COPY go.mod go.sum ./
ну так проще и понятнее  одна команда вместо 7 и - этот образ не будет использоваться

2024-09-02 12:16 UTC, dirtymew approved these changes
Никита

задание считаю выполненным

поздравляю и желаю удачи

2024-09-02 12:21 UTC, dirtymew commented on internal/services/task_service.go
> +package services
лучше так task/service.go

2024-09-02 12:21 UTC, dirtymew commented on internal/handlers/task_handler.go
> +	"gofinalproject/config"
тут форматирование импортов поехало...

2024-09-02 12:21 UTC, dirtymew commented on cmd/app/main.go
> +	"gofinalproject/config"
и тут - go imports c флагом local

2024-09-02 20:04 UTC, DoomProger commented on internal/repositories/task_repository.go
> +		"SELECT * FROM scheduler ORDER BY date LIMIT :limit", sql.Named("limit", config.Limit50))
Понял принял, спасибо

2024-09-02 20:18 UTC, DoomProger commented on internal/handlers/task_handler.go
> +	"gofinalproject/config"
Странно, локально у меня норм
![image](https://github.com/user-attachments/assets/5faeeeda-d74c-41e0-aed1-bc9d8e0ce2c9)

2024-09-02 20:38 UTC, DoomProger commented on cmd/app/main.go
> +	"gofinalproject/config"
Вроде поправил

2024-09-02 20:39 UTC, DoomProger commented
> Никита
> 
> задание считаю выполненным
> 
> поздравляю и желаю удачи

Спасибо! И тебе удачи)

2024-09-02 20:40 UTC, merged